# 数据源配置
spring:
  datasource:
    name: newbee-mall-datasource
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://119.29.13.56:3306/zxx?serverTimezone=UTC&allowMultiQueries=true
    username: zxx
    password: wG6drpdSa38mz8LN
    hikari:
      pool-name: hikariCP
      minimum-idle: 100
      maximum-pool-size: 200
      auto-commit: true
      idle-timeout: 10000
      max-lifetime: 30000
      connection-timeout: 30000
      connection-test-query: SELECT 1
  redis:
    host: 119.29.13.56
    port: 6379
#    password:
    timeout: 5000ms
    connect-timeout: 5000ms
    expire: 400
    client-type: lettuce
    lettuce:
      pool:
        max-wait: -1
        max-idle: 5
        min-idle: 0
        max-active: 20
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
