
# 服务器配置
server:
  port: 8081
  undertow:
    buffer-size: 1024
    direct-buffers: true
    threads:
      io: 16
      worker: 256
  servlet:
    session:
      tracking-modes: cookie
    context-path: / # 打包成war包不加访问路径不加项目名


# 项目全局配置
#project:
#  name: zxx # 项目名称
#  #  fileUploadPath: /opt/newbee-mall-plus/upload/  # 上传文件的默认url前缀，根据部署设置自行修改，linux下路径
#  fileUploadPath: D:\\upload\\              # 上传文件的默认url前缀，根据部署设置自行修改，windows下路径
#  orderUnpaidOverTime: 300 # 订单未支付超期时间，单位秒
#  serverUrl: http://localhost:8081 # 服务器地址

# spring配置
spring:
  mvc:
    static-path-pattern: /static/**
  thymeleaf:
    cache: false  #cache: 是否缓存，开发模式下设置为false，避免改了模板还要重启服务器，线上设置为true，可以提高性能。
    prefix: classpath:/templates/
    suffix: .html
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  profiles:
    active: dev  # @activatedProperties@对应pom.xml的<activatedProperties>标签吗，其中哪个标签的<activeByDefault>的值为true就使用哪个环境
  mail:
    host: smtp.qq.com
    username: 2443597469@qq.com
    password: twhsusqbpojvebeb
  web:
    resources:
      static-locations: classpath:/static/
# mybatis配置
#mybatis:
#  mapper-locations: classpath:mappers/*Mapper.xml    # mapper映射文件位置
#  type-aliases-package: com.Pojo
#  configuration:
#    map-underscore-to-camel-case: false

mybatis-plus:
  mapper-locations: classpath:mappers/*Mapper.xml    # mapper映射文件位置
  type-aliases-package: com.Pojo
  configuration:
    map-underscore-to-camel-case: false

#分页插件
pagehelper:
  helper-dialect: mysql
  #  params=count: countSql
  reasonable: true
  support-methods-arguments: true

# alipay 需要自行申请支付宝的沙箱账号、申请appID，并依次配置AppID、密钥、公钥，否则无法发起支付宝支付。
#alipay:
#  app-id:
#  rsa-private-key:
#  alipay-public_key:
#  gateway: https://openapi.alipaydev.com/gateway.do
#  charset: UTF-8
#  format: json
#  #  log-path: /opt/newbee-mall-plus/log
#  log-path: D://newbee-mall-plus//log
#  signtype: RSA2


